export { default as GettingStarted } from './GettingStarted'
export { default as Login } from './Login'
export { default as SignIn } from './SignIn'
export { default as Register } from './Register'
export { default as Home } from './Home'
export { default as Search } from './Search'
export { default as Favorite } from './Favorite'
export { default as Profile } from './Profile'
